// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shgleofaaznrtvupylzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoZ2xlb2ZhYXpucnR2dXB5bHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjI5NDksImV4cCI6MjA2MzkzODk0OX0.oc1_5a4weqWEgOrbBFKBEqWY3fTv-TwMqbrvRLorMdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);